name: NoSpawnerForAfk
version: 1.1.0
author: pmme
description: Block spawn events from spawners if all nearby players are AFK in Essentials
main: nz.pmme.nospawnerforafk.NoSpawnerForAfk
api-version: 1.15
depend: [Essentials]
softdepend: [EpicSpawners]

commands:
  nospawnerforafk:
    description: NoSpawnerForAfk commands
    usage: /nospawnerforafk [on|off|range|log]

permissions:
  nospawnerforafk.enable:
    description: Allow enable or disable of plugin.
    default: op
  nospawnerforafk.setrange:
    description: Players with this permission can set the range to check for players.
    default: op
  nospawnerforafk.log:
    description: Players with this permission can enable or disable debug logging.
    default: op
  nospawnerforafk.bypass:
    description: Players with this permission can still get spawns from spawners when AFK.
    default: false
  nospawnerforafk.*:
    description: Grant all permissions.
    default: false
    children:
      nospawnerforafk.enable: true
      nospawnerforafk.setrange: true
      nospawnerforafk.bypass: true
      nospawnerforafk.log: true
